server:
  ip: 127.0.0.1
  port: 8080
  mode: debug

mysql:
  user: root
  password: 12345678
  ip: 127.0.0.1
  port: 3306
  db: test

zap:
  fileStdout: true
  consoleStdout: true
  level: debug
  path: log/server.log
  maxSize: 111
  maxAge: 111
  maxBackups: 111
  localTime: true
  compress: true